// Blunder Buster — chrome.storage wrappers + game result cache

const CACHE_KEY       = 'analyzedGames';
const MAX_CACHED_GAMES = 20;

// ── Session storage (volatile, cleared on browser restart) ──────────────────

export const session = {
  get: (keys) => chrome.storage.session.get(keys),
  set: (data) => chrome.storage.session.set(data),
  remove: (keys) => chrome.storage.session.remove(keys),
};

// ── Local storage (persistent) ───────────────────────────────────────────────

export const local = {
  get:  (keys) => chrome.storage.local.get(keys),
  set:  (data) => chrome.storage.local.set(data),

  async getSettings() {
    const defaults = {
      analysisDepth: 20,
      autoAnalyze:   true,
      showBestMove:  true,
      boardTheme:    'default',
      claudeApiKey:  '',
      coachEnabled:  true,
    };
    const stored = await chrome.storage.local.get(Object.keys(defaults));
    return { ...defaults, ...stored };
  },

  async saveSettings(settings) {
    return chrome.storage.local.set(settings);
  },
};

// ── Game analysis cache (LRU, max 20 games) ──────────────────────────────────

/**
 * Load all cached analysis entries (array, newest first).
 * @returns {Promise<Array<{gameId:string, timestamp:number, data:object}>>}
 */
async function loadCache() {
  const result = await chrome.storage.local.get([CACHE_KEY]);
  return result[CACHE_KEY] ?? [];
}

/**
 * Save a completed analysis result for a game.
 * @param {string} gameId
 * @param {object} analysisData  — the full analysis result
 */
export async function cacheAnalysis(gameId, analysisData) {
  let cache = await loadCache();

  // Remove existing entry for this game if present
  cache = cache.filter(entry => entry.gameId !== gameId);

  // Prepend new entry
  cache.unshift({ gameId, timestamp: Date.now(), data: analysisData });

  // Enforce max size
  if (cache.length > MAX_CACHED_GAMES) {
    cache = cache.slice(0, MAX_CACHED_GAMES);
  }

  await chrome.storage.local.set({ [CACHE_KEY]: cache });
}

/**
 * Retrieve a cached analysis by gameId.
 * @param {string} gameId
 * @returns {Promise<object|null>}
 */
export async function getCachedAnalysis(gameId) {
  const cache = await loadCache();
  return cache.find(entry => entry.gameId === gameId)?.data ?? null;
}

/**
 * Clear all cached analyses.
 */
export async function clearCache() {
  await chrome.storage.local.remove([CACHE_KEY]);
}

// ── Coach explanation cache ───────────────────────────────────────────────────

const COACH_CACHE_KEY = 'coachCache';
const MAX_COACH_ENTRIES = 500;
const COACH_EVICT_COUNT = 100;

/**
 * Retrieve a cached coach explanation for a specific move.
 * @param {string} gameId
 * @param {number} moveIndex
 * @returns {Promise<{text:string, isAI:boolean, ts:number}|null>}
 */
export async function getCoachExplanation(gameId, moveIndex) {
  const result = await chrome.storage.local.get([COACH_CACHE_KEY]);
  const cache  = result[COACH_CACHE_KEY] ?? {};
  return cache[`${gameId}:${moveIndex}`] ?? null;
}

/**
 * Save a coach explanation for a specific move.
 * @param {string}  gameId
 * @param {number}  moveIndex
 * @param {string}  text
 * @param {boolean} isAI   true if generated by Claude
 */
export async function saveCoachExplanation(gameId, moveIndex, text, isAI) {
  const result = await chrome.storage.local.get([COACH_CACHE_KEY]);
  const cache  = result[COACH_CACHE_KEY] ?? {};

  cache[`${gameId}:${moveIndex}`] = { text, isAI, ts: Date.now() };

  // Evict oldest entries if over cap
  const entries = Object.entries(cache);
  if (entries.length > MAX_COACH_ENTRIES) {
    entries.sort((a, b) => a[1].ts - b[1].ts);
    for (let i = 0; i < COACH_EVICT_COUNT; i++) {
      delete cache[entries[i][0]];
    }
  }

  await chrome.storage.local.set({ [COACH_CACHE_KEY]: cache });
}
